/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package görsellabproje;

import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Windows 8.1
 */
public class AnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenü
     */
    static ArrayList<ogrenci> ogrenciListesi=new ArrayList<ogrenci>();
    static ArrayList<notlar> notlarListesi=new ArrayList<notlar>();
    int sayac=0;
    public AnaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DersAd = new javax.swing.JTextField();
        DersEkle = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dersListesi = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        kredi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Ad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Soyad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Eposta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Adres = new javax.swing.JTextField();
        Kaydet = new javax.swing.JButton();
        Temizle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Numara = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        OgrenciListe = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ÖgrenciSorg = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ÖgrNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Ders = new javax.swing.JComboBox<>();
        Ünlem = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        NotunuGir = new javax.swing.JTextField();
        Kaydet1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotListe = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        SistemdenÇıkış = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        setForeground(java.awt.Color.red);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(153, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("DERS İŞLEMLERİ KATEGORİSİ \n\n1) DERS ADI BÖLÜMÜNE İSTEDİĞİMİZ DERSİ YAZIYORUZ.\n2) KARŞISINA DERSİN KREDİSİNİ YAZIYORUZ.\n3) ALT PANELDE BU YAZILANLAR KAYDET BUTONUNA BASILARAK GÖSTERİLECEKTİR.\n\nÖĞRENCİ EKLEME KATEGORİSİ \n\n1) ÖĞRENCİYE DAİR AD,SOYAD,NUMARA,ADRES,EPOSTA BİLGİLERİNİ GİRİYORUZ.\n2)YAN PANELDE BU YAZILANLAR KAYDET BUTONUYLA GÖSTERİLECEKTİR.\n\nÖĞRENCİ SORGULAMA KATEGORİSİ \n\n1)ÖĞRENCİ EKLEMEDE KAYIT EDİLEN ÖĞRENCİ NUMARASI İLE SORGULAMA YAPILACAKTIR.\n2)SOL PANELDE KİŞİSEL BİLGİLER SAĞ PANELDE NOT BİLGİLERİ GÖSTERİLECEKTİR.\n\nNOT EKLEME KATEGORİSİ\n\n1) EKLENEN ÖĞRENCİLERİN NUMARASI İLE GİRİŞ YAPILACAKTIR.\n2) BURAYA TIKLA'YA BİR KEZ BASILDIĞINDA YENİ DERSLER GÖSTERİLECEKTİR. BİR KEZ DAHA\nBASILDIĞINDA ESKİ DERSLER GÖSTERİLECEKTİR.\n3)ÖĞRENCİNİN DERSTEN ALDIĞI NOT GİRİLECEKTİR.\n4)ALT PANELDE BUNLAR GÖZÜKECEKTİR.\n\n");
        jScrollPane5.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        jTabbedPane1.addTab("OBS Nasıl Çalışır", jPanel5);

        jPanel2.setForeground(new java.awt.Color(153, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Ders Adı :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 61, 26));
        jPanel2.add(DersAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, 30));

        DersEkle.setText("Dersi Ekle");
        DersEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DersEkleActionPerformed(evt);
            }
        });
        jPanel2.add(DersEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 560, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("DERS İŞLEMLERİ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        dersListesi.setColumns(20);
        dersListesi.setRows(5);
        jScrollPane2.setViewportView(dersListesi);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 145, 600, 216));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 255));
        jLabel22.setText("Dersin Kredisi :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 54, -1, 20));
        jPanel2.add(kredi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 130, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows 8.1\\Documents\\NetBeansProjects\\GörselLabProje\\src\\Resimler\\aa.png")); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        jTabbedPane1.addTab("Ders İşlemleri", null, jPanel2, "");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText(" Adı : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, 29));
        jPanel1.add(Ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Soyadı :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 26));
        jPanel1.add(Soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("ÖĞRENCİ BİLGİLERİ");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 200, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("E-posta :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 50, -1));
        jPanel1.add(Eposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Adres :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, -1));

        Adres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(Adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 120, 30));

        Kaydet.setText("Kaydet");
        Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetActionPerformed(evt);
            }
        });
        jPanel1.add(Kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 30));

        Temizle.setText("Temizle");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });
        jPanel1.add(Temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("Numarası :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(Numara, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, 30));

        OgrenciListe.setColumns(20);
        OgrenciListe.setRows(5);
        jScrollPane3.setViewportView(OgrenciListe);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 390, 190));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows 8.1\\Documents\\NetBeansProjects\\GörselLabProje\\src\\Resimler\\Gece-deniz-manzaraları.jpg")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 430));

        jTabbedPane1.addTab("Öğrenci Ekleme", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("Öğrenci Sorgulama :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 126, 27));

        ÖgrenciSorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÖgrenciSorgActionPerformed(evt);
            }
        });
        ÖgrenciSorg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ÖgrenciSorgKeyReleased(evt);
            }
        });
        jPanel4.add(ÖgrenciSorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 520, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("ÖĞRENCİ NUMARASIYLA ÖĞRENCİ SORGULAMA");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jScrollPane6.setViewportView(tablo);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 400, 260));

        jScrollPane4.setViewportView(jTable1);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 220, 260));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows 8.1\\Documents\\NetBeansProjects\\GörselLabProje\\src\\Resimler\\aa.png")); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        jTabbedPane1.addTab("Öğrenci Sorgula", jPanel4);

        jPanel3.setForeground(new java.awt.Color(102, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setText("Öğrenci Numarası : ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 54, -1, 22));
        jPanel3.add(ÖgrNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 55, 140, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("Dersini Seç : ");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 91, 94, -1));

        Ders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DersActionPerformed(evt);
            }
        });
        jPanel3.add(Ders, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 88, 140, -1));

        Ünlem.setText("Buraya Tıkla");
        Ünlem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÜnlemActionPerformed(evt);
            }
        });
        jPanel3.add(Ünlem, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 87, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setText("Notunu Giriniz :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 131, -1, -1));
        jPanel3.add(NotunuGir, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 128, 140, -1));

        Kaydet1.setText("Kaydet");
        Kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kaydet1ActionPerformed(evt);
            }
        });
        jPanel3.add(Kaydet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 166, 150, -1));

        NotListe.setColumns(20);
        NotListe.setRows(5);
        jScrollPane1.setViewportView(NotListe);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 620, 190));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setText("NOT LİSTESİ ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 195, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 255));
        jLabel15.setText("ÖĞRENCİ NOT EKLEME");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 330, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows 8.1\\Documents\\NetBeansProjects\\GörselLabProje\\src\\Resimler\\Gece-deniz-manzaraları.jpg")); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        jTabbedPane1.addTab("Not Ekleme", jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 0, 0);
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("TECHNOEİN ÖĞRENCİ BİLGİ SİSTEMİNE HOŞGELDİNİZ  | www.technoein.com ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 80, 0, 0);
        getContentPane().add(jLabel16, gridBagConstraints);

        SistemdenÇıkış.setText("Sistemden Çıkış");
        SistemdenÇıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SistemdenÇıkışActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 0);
        getContentPane().add(SistemdenÇıkış, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SistemdenÇıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemdenÇıkışActionPerformed
        dispose();
    }//GEN-LAST:event_SistemdenÇıkışActionPerformed

    private void Kaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kaydet1ActionPerformed

        int sayac=0;
        for (int i = 0; i < ogrenciListesi.size(); i++)
        {
            if(ogrenciListesi.get(i).getOgrenciNumarasi().equalsIgnoreCase(ÖgrNo.getText()))
            {
                sayac++;
            }
        }
        if(sayac>0)
        {
            NotListe.setText("\n"+ÖgrNo.getText()+" "+Ders.getSelectedItem()+" "+NotunuGir.getText()+NotListe.getText());
            notlar notlarNesnesi=new notlar((String)Ders.getSelectedItem(),NotunuGir.getText(),ÖgrNo.getText());
            notlarListesi.add(notlarNesnesi);

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sistemimize kayıtlı böyle bir öğrenci bulunamadı.","Error 404",JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Kaydet1ActionPerformed

    private void ÜnlemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÜnlemActionPerformed
        String erdal= DersAd.getText();
        StringTokenizer st =new StringTokenizer(erdal," ");
        if(sayac==0)
        {
            while(st.hasMoreElements())
            {
                Ders.addItem(st.nextToken());

            }
            sayac++;
        }
        else
        {
            while(st.hasMoreElements())
            {
                Ders.removeItem(st.nextToken());

            }

            sayac=0;
        }
    }//GEN-LAST:event_ÜnlemActionPerformed

    private void DersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DersActionPerformed

    private void ÖgrenciSorgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ÖgrenciSorgKeyReleased
        // TODO add your handling code here:
        String dizim[][]=new String[ogrenciListesi.size()][];

        for (int i = 0; i < ogrenciListesi.size(); i++) {
            if(ogrenciListesi.get(i).getOgrenciNumarasi().equalsIgnoreCase(ÖgrenciSorg.getText()))
            {
                dizim[i]=new String[]{
                    ogrenciListesi.get(i).getOgrenciNumarasi(),
                    ogrenciListesi.get(i).getOgrenciAdi(),
                    ogrenciListesi.get(i).getOgrenciSoyadi(),
                    ogrenciListesi.get(i).getOgrenciAdres(),
                    ogrenciListesi.get(i).getOgrenciEposta()
                };
            }
        }
        TableModel tabloModeli=new DefaultTableModel (
            dizim,
            new String[] {"Öğrenci No", "İsim", "Soyisim", "Adres","Eposta"}
        );
        tablo.setModel(tabloModeli);

        /*----------------------------------------*/
        String dizim2[][]=new String[notlarListesi.size()][];

        for (int i = 0; i < notlarListesi.size(); i++) {
            if(notlarListesi.get(i).getOgrenciNumarasi().equalsIgnoreCase(ÖgrenciSorg.getText()))
            {
                dizim2[i]=new String[]{
                    notlarListesi.get(i).getDersAdi(),
                    notlarListesi.get(i).getDersNotu(),

                };
            }
        }
        TableModel tabloModeli2=new DefaultTableModel (
            dizim2,
            new String[] {"Dersler", "Notlar"}
        );
        jTable1.setModel(tabloModeli2);
    }//GEN-LAST:event_ÖgrenciSorgKeyReleased

    private void ÖgrenciSorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÖgrenciSorgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ÖgrenciSorgActionPerformed

    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed

        Ad.setText("");
        Soyad.setText("");
        Eposta.setText("");
        Adres.setText("");
    }//GEN-LAST:event_TemizleActionPerformed

    private void KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetActionPerformed
        OgrenciListe.setText(OgrenciListe.getText()+Ad.getText()+" "+Soyad.getText()+" "+Numara.getText()+" "+Eposta.getText()+" "+Adres.getText()+"\n");
        ogrenci ogrenciNesnesi=new ogrenci();
        ogrenciNesnesi.setOgrenciAdi(Ad.getText());
        ogrenciNesnesi.setOgrenciSoyadi(Soyad.getText());
        ogrenciNesnesi.setOgrenciNumarasi(Numara.getText());
        ogrenciNesnesi.setOgrenciEposta(Eposta.getText());
        ogrenciNesnesi.setOgrenciAdres(Adres.getText());
        ogrenciListesi.add(ogrenciNesnesi);
    }//GEN-LAST:event_KaydetActionPerformed

    private void DersEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DersEkleActionPerformed
        dersListesi.setText(dersListesi.getText()+"Dersin Adı : " + DersAd.getText()+" Dersin Kredisi : "+kredi.getText()+"\n");
    }//GEN-LAST:event_DersEkleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ad;
    private javax.swing.JTextField Adres;
    private javax.swing.JComboBox<String> Ders;
    private javax.swing.JTextField DersAd;
    private javax.swing.JButton DersEkle;
    private javax.swing.JTextField Eposta;
    private javax.swing.JButton Kaydet;
    private javax.swing.JButton Kaydet1;
    private javax.swing.JTextArea NotListe;
    private javax.swing.JTextField NotunuGir;
    private javax.swing.JTextField Numara;
    private javax.swing.JTextArea OgrenciListe;
    private javax.swing.JButton SistemdenÇıkış;
    private javax.swing.JTextField Soyad;
    private javax.swing.JButton Temizle;
    private javax.swing.JTextArea dersListesi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField kredi;
    private javax.swing.JTable tablo;
    private javax.swing.JTextField ÖgrNo;
    private javax.swing.JTextField ÖgrenciSorg;
    private javax.swing.JButton Ünlem;
    // End of variables declaration//GEN-END:variables

    private void Dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
